name: Python CI Pipeline

on: [push]

env:
  DOCKER_IMAGE_NAME: ""
  PYTHON_APP_SOURCE_DIR: "."
  PYTEST_COVERAGE_XML_FILE_NAME: "coverage-reports/coverage-pytest.xml"
  PYTEST_COVERAGE_THRESHOLD_PERCENT: 50

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      packages: write
      actions: read
      security-events: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Custom Python Poetry CI action
      uses: ./.github/actions/build
      with: 
        pytest_coverage_xml_file_name: ${{ env.PYTEST_COVERAGE_XML_FILE_NAME }}
        source_dir: ${{ env.PYTHON_APP_SOURCE_DIR }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gitleaks_token: ${{ secrets.GITLEAKS_TOKEN }}
        pytest_coverage_threshold_percent: ${{ env.PYTEST_COVERAGE_THRESHOLD_PERCENT }}

    - name: Test Dockerfile 
      uses: ./.github/actions/test
      with:
        docker_repo_name: ${{ env.DOCKER_IMAGE_NAME || github.event.repository.name }}
    
    - name: Deploy Dockerfile 
      if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
      uses: ./.github/actions/test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        docker_repo_name: ${{ env.DOCKER_IMAGE_NAME || github.event.repository.name }}